export const topic2MCQAnswers = [
    {id: "2.1.1", options: [
        {textId: "1", text: "value =  {text}"},
        {textId: "2", text: "onChange={(e) => setState(e.target.value)}"},
        {textId: "3", text: "type = 'text'"},
        {textId: "4", text: "placeholder = 'Enter text'"},
    ],
    correctId: "3"},
    {id: "2.1.2", options: [
        {textId: "1", text: "<Form.Group>"},
        {textId: "2", text: "<Form.Label>"},
        {textId: "3", text: "<Form.Control>"},
        {textId: "4", text: "<Form.Text>"},
    ],
    correctId: "3"},
    {id: "2.1.3", options: [
        {textId: "1", text: "value and onClick"},
        {textId: "2", text: "onChange and placeholder"},
        {textId: "3", text: "type and placeholder"},
        {textId: "4", text: "value and onChange"},
    ],
    correctId: "4"},
    {id: "2.1.4", options: [
        {textId: "1", text: "value"},
        {textId: "2", text: "readOnly"},
        {textId: "3", text: "disabled"},
        {textId: "4", text: "type"},
    ],
    correctId: "1"},
    {id: "2.1.5", options: [
        {textId: "1", text: "onClick"},
        {textId: "2", text: "onFocus"},
        {textId: "3", text: "onChange"},
        {textId: "4", text: "onLoad"},
    ],
    correctId: "3"},
    {id: "2.1.6", options: [
        {textId: "1", text: "onChange"},
        {textId: "2", text: "placeholder"},
        {textId: "3", text: "readOnly"},
        {textId: "4", text: "disabled"},
    ],
    correctId: "1"},
    {id: "2.1.7", options: [
        {textId: "1", text: "useEffect"},
        {textId: "2", text: "useState"},
        {textId: "3", text: "useRef"},
        {textId: "4", text: "useContext"},
    ],
    correctId: "2"},
    {id: "2.1.8", options: [
        {textId: "1", text: "value"},
        {textId: "2", text: "defaultValue"},
        {textId: "3", text: "event.target.value"},
        {textId: "4", text: "event.target.defaultValue"},
    ],
    correctId: "3"},
    {id: "2.1.9", options: [
        {textId: "1", text: "use the input name attribute to identify which field to update in the state"},
        {textId: "2", text: "use a separate onChange handler for each form control that updates the corresponding state variable"},
        {textId: "3", text: "use the className attribute to bind each form control to its corresponding state variable"},
        {textId: "4", text: "use the controlId attribute to bind each form control to its corresponding state variable"},
    ],
    correctId: "1"},
]